on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm install
 
      - uses: JS-DevTools/npm-publish@v1
        env:
          TESTING: "1.3.0"
        if: ${{contains(env.TESTING, 'beta')}}
        with:
          token: ${{ secrets.NPM_TOKEN }}
