name: Release
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to npm
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: 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
